export type AdminBillingPlan = {
  id: string;
  name: string;
  priceMonthly: number;
  projectsLimit: number;
  campaignsLimit: number;
  questsLimit: number;
  raidsLimit: number;
  providersLimit: number;
  includedBillableSeats: number;
  sortOrder: number;
  trialDays: number;
  currency: string;
  billingInterval: string;
  isPublic: boolean;
  isSelfServe: boolean;
  isCheckoutEnabled: boolean;
  isFreeTier: boolean;
  isEnterprise: boolean;
  featureFlags: Record<string, unknown>;
  entitlementMetadata: Record<string, unknown>;
  stripeProductId?: string;
  stripeMonthlyPriceId?: string;
  features: string[];
  current?: boolean;
};
